import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import "./globals.css";
import Logout from "./logout";
import Link from "next/link";
import { NextAuthProvider } from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <NextAuthProvider>
      <html lang="en">
      <body className={inter.className}>
      <nav>
          {!!session && <Logout />}
        </nav>
        {children}</body>
      </html>
    </NextAuthProvider>
  );
}
