version: '3'
services:
  directus:
    image: directus/directus:10.8.2
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      KEY: YOUR_RANDOMLY_GENERATED_KEY
      SECRET: YOUR_RANDOMLY_GENERATED_SECRET
      ADMIN_EMAIL: ADMIN_EMAIL
      ADMIN_PASSWORD: ADMIN_PASSWORD
      DB_CLIENT: YOUR_DB
      DB_HOST: host.docker.internal #LOCAL_HOST_IN_DOCKER
      DB_PORT: YOUR_DB_PORT
      DB_DATABASE: YOUR_DB_TABLE
      DB_USER: YOUR_DB_USER
      DB_PASSWORD: YOUR_DB_USER_PASSWORD
      WEBSOCKETS_ENABLED: true
      CORS_ENABLED: true
      EXTENSIONS_AUTO_RELOAD: true
      EXTENSIONS_MUST_LOAD: true
      EXTENSIONS_PATH: ./extensions
      PASSWORD_RESET_URL_ALLOW_LIST: http://localhost:3000/reset-password
      EMAIL_FROM: EMAIL@YOURDOMAIN.COM
      EMAIL_TRANSPORT: smtp
      # Email (SMTP Transport)
      # EMAIL_SMTP_POOL=true
      EMAIL_SMTP_HOST: YOUR_SMTP_HOST_SERVER
      EMAIL_SMTP_PORT: 465
      EMAIL_SMTP_USER: EMAIL@YOURDOMAIN.COM
      EMAIL_SMTP_PASSWORD: YOUR_SMTP_USER_PASSWORD
      EMAIL_SMTP_SECURE: true
      EMAIL_SMTP_NAME: YOUR_SMTP_NAME



